### ISSUE TITLE
GET request for images always get sent twice

### ISSUE THREAD

**Issue by jjbutler74** [postmanlabs/postman-app-support#615]
A plain GET request of an image always creates two identical request (a few milliseconds apart).

I tested this GET request:
http://www.getpostman.com/img/screens/home.png

And recorded this responds:
![image](https://cloud.githubusercontent.com/assets/7923597/3314192/349a1ee8-f6ee-11e3-915d-9887d7c416a3.png)

This has been observed in various scenarios and on several different machines..

**Comment by rbalik** [comment]
Just wanted to chime in that I'm seeing this issue in the packaged app.
I'm doing a plain GET over HTTPS for an image/png without any url parameters.

**Comment by rbalik** [comment]
Oh and it happens with regular HTTP as well.

**Comment by ehoesch** [comment]
I have the packaged app 2.0.5. The error still occurs!!!!! Has it become a feature?

**Comment by abhijitkane** [comment]
This has been fixed in the latest release. @ehoesch can you confirm?

**Comment by waderyan** [comment]
I'm still seeing this.

Version 3.0.2 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

How to reproduce?
1 - Click Send in Postman

```
GET /img/screens/home.png HTTP/1.1
Host: www.getpostman.com
Cache-Control: no-cache
```

2 - Observe Http traffic

![image](https://cloud.githubusercontent.com/assets/2449568/8555705/f1e43fd0-24ae-11e5-99e4-04e6307f524c.png)

**Comment by rbwendt** [comment]
I'm seeing this too. Interestingly, the second request isn't sending the same headers as the first. In my case, the second request is missing an `Authorization` header.

**Comment by Wilt** [comment]
Same as @rbwendt for me. `Authorization` header is missing totally but on top of that the `Accept` header is changed from `image/png` to `image/webp,*/*;q=0.8`

**Comment by anothermh** [comment]
This is definitely still happening in:

```
Version 3.0.13 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64
```

Can we please have this issue reopened?

**Comment by abhijitkane** [comment]
@anothermh @Wilt 
I'm sending a GET request to http://www.getpostman.com/img/logo.png, (interceptor disabled), and seeing only one request (tried with https too) in the server logs. Are there any specific images you see this for? Also, how are you determining that the request is sent twice?

This happens for pdf files because Postman has to re-send the request with `xhr.responsetype` set to `arraybuffer`, but I'm not sure why it should be happening for images.

**Comment by anothermh** [comment]
I am using a Rails controller to generate and render an image to the client. The Rails controller uses [send_data](http://apidock.com/rails/ActionController/Streaming/send_data) to render to the client. When I request this endpoint with Postman it renders twice:

```
Started GET "/b7934fb1ad8f1ff106dec2bb8917a603b0dff99a/4a438eb2eb7ff3d86e784c96bef5a3b9e393cc29/image.jpg" for ::1 at 2015-09-05 12:08:36 -0700
Processing by ExampleController#send_image as JPEG
  Parameters: {"hash_one"=>"b7934fb1ad8f1ff106dec2bb8917a603b0dff99a", "hash_two"=>"4a438eb2eb7ff3d86e784c96bef5a3b9e393cc29", "image_name"=>"image"}
  Rendered text template (0.2ms)
Sent data image.jpg (11.5ms)
Completed 200 OK in 12737ms (Views: 11.3ms | ActiveRecord: 4725.1ms)


Started GET "/b7934fb1ad8f1ff106dec2bb8917a603b0dff99a/4a438eb2eb7ff3d86e784c96bef5a3b9e393cc29/image.jpg" for ::1 at 2015-09-05 12:08:49 -0700
Processing by ExampleController#send_image as JPEG
  Parameters: {"hash_one"=>"b7934fb1ad8f1ff106dec2bb8917a603b0dff99a", "hash_two"=>"4a438eb2eb7ff3d86e784c96bef5a3b9e393cc29", "image_name"=>"image"}
  Rendered text template (0.3ms)
Sent data image.jpg (0.8ms)
Completed 200 OK in 2136ms (Views: 0.7ms | ActiveRecord: 1648.1ms)
```

When I make the same request using curl or a browser like Chrome, Firefox, or Safari, the controller and actions are only fired once. The logs show only a single inbound request (omitting the log since it's obviously only one request in the log when fired by browser).

Here are the headers returned when I view the response in Postman (after a double render):

```
Cache-Control → no-cache, no-store
Content-Disposition → attachment; filename="image.jpg"
Content-Length → 11145
Content-Transfer-Encoding → binary
Content-Type → image/jpg
Expires → Sat, 26 Jul 1997 05:00:00 GMT
Pragma → no-cache
X-Content-Type-Options → nosniff
X-Frame-Options → SAMEORIGIN
X-Request-Id → 18e60be8-59e0-4ae1-bfa6-e6e8e3e624ed
X-Runtime → 2.325739
X-XSS-Protection → 1; mode=block
```

Here are the headers returned when I view the response in `curl --head -XGET` (which works normally and does only a single render): 

```
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: image/jpg
Expires: Sat, 26 Jul 1997 05:00:00 GMT
Content-Disposition: attachment; filename="image.jpg"
Content-Transfer-Encoding: binary
X-Request-Id: ee9e77ce-b2e3-41e6-97e2-a9e2b60cae79
X-Runtime: 2.261185
Content-Length: 11145
```

**Comment by anothermh** [comment]
One thing I missed was disabling Interceptor, which has stopped the double render. Can you help me understand why that causes that issue?

**Comment by abhijitkane** [comment]
The Interceptor seems to be resending the request with responsetype=arraybuffer if it's an image. There doesn't seem to be a need to do that, since Postman is the one that renders the response. We've pushed a fix - can you update to version 0.2.12 of the Interceptor (chrome:/extensions, Developer Mode > Update extensions now) and check?

**Comment by anothermh** [comment]
I can confirm that the problem has been resolved in 0.2.12 of Interceptor. The GET request is only seen once in the server logs. Thank you for quickly resolving this.

**Comment by ajsjunior** [comment]
The same problem is happening with media type **application/pdf**.
How to fix this?

**Comment by novabe** [comment]
Also Seeing this with PDF, version:
4.9.2
win / x86-32
Chrome 56.0.2924.76
