### ISSUE TITLE
In Environment, Empty 'current value' should take 'Initial value' for any variale

### ISSUE THREAD

**Issue by ronakkhunt** [postmanlabs/postman-app-support#7179]
**Is your feature request related to a problem? Please describe.**
In environment, any variable should assume 'initial value' when 'current value' field is empty. This helps when you want have some tests with temporary value. Right now, leaving empty 'current values' does not do anything. 'Initial values' has no meaning in this sense, as you always have to have 'current value'.

**Describe the solution you'd like**
In environment, when, for any variable, 'current value' is empty it should take 'initial value'.

**Comment by shamasis** [comment]
Interesting. I’m adding this to our list and would look into it as soon as we are done with our initial rounds of improvements that we have planned for environments.

**Comment by jasonmcboyd** [comment]
To be honest, I thought this _is_ how it was supposed to behave. Unless I am misinterpreting the tooltip that comes up when you hover over the 'current value' column header (emphasis mine):

> This value is used while sending a request. Current values are never synced to Postman's servers. **If left untouched, the current value automatically assumes the initial value.**

**Comment by kcak11** [comment]
> To be honest, I thought this _is_ how it was supposed to behave. Unless I am misinterpreting the tooltip that comes up when you hover over the 'current value' column header (emphasis mine):
> 
> > This value is used while sending a request. Current values are never synced to Postman's servers. **If left untouched, the current value automatically assumes the initial value.**

I believe the purpose of "Initial Value" is to populate the "Current Value" when the "Reset All" button is clicked.
As per the tooltip for "Reset All":
![image](https://user-images.githubusercontent.com/703559/79442918-cc084d80-7ff6-11ea-88ac-4fc98b7d1cd8.png)
Note: If you click the more options, you will find the "Reset" option in every row which does the similar copy Initial -> Current for the current row.

It is just the reverse of "Persist All":
![image](https://user-images.githubusercontent.com/703559/79443000-e2160e00-7ff6-11ea-9732-a0f0c5287b81.png)
Note: If you click the more options, you will find the "Persist" option in every row which does the similar copy Current -> Initial for the current row.

So for a value to get passed into a request, it **always** needs to be in the "Current Value" field and needs manual effort of clicking either the "Reset" or "Reset All" or typing-in the value. I believe that is the current implementation.

**Comment by Nielwulf** [comment]
I'm still running into this problem. Currently when sharing a Collection, even if the 'initial value' is set, it does NOT read that value when shared. The 'current value' tooltip verbage would indicate that the 'initial value' would be used IF there is no 'current value.'

The tooltip reads: This value is used while sending a request. Current values are never synced to Postman's servers. If left untouched, the current value automatically assumes the initial value.

If I click 'Reset All' it will set the current value to that of the initial value, but from what the tooltip states, that shouldn't be a necessary step.

**Comment by janArb** [comment]
I wouldn't call this a feature, but a bug.

**Comment by matpag** [comment]
Same here, I would expect initial value to be picked as default if current value is missing

**Comment by alec-irl** [comment]
Don't get why this is still an outstanding issue. What exactly is the desired way for this to work? Because as a user I'm having a hard time understanding.

**Comment by Alcas1** [comment]
This definitely seems like a bug, programatic usage of environment variables is very common. Not sure why this bug is still here

**Comment by dannythunder** [comment]
This should be fixed. Pretty stupid design if this is as intended.

**Comment by ezequieldelucaey** [comment]
Is there any expected date for this to be resolved? This bug is still present on the current version of postman

**Comment by imitroshyn** [comment]
same here. this is definitely not "feature"

**Comment by wjling** [comment]
This is definitely a bug which can be easily solved. I'm surprised that this bug has existed so many years

**Comment by jonathansds** [comment]
Any update or estimate for when this should be changed/fixed? Soon enough it's gonna be 4 years into this...

**Comment by marty-tormoehlen** [comment]
Still seems like a problem.

**Comment by JamesGanzer** [comment]
This is still an issue. If current is empty, it will not use initial value and will use the empty current value instead.

**Comment by rickychew77** [comment]
I concur, its been years but bug still persists.

**Comment by mustaphadem** [comment]
+1

**Comment by Alcas1** [comment]
Relabel feature as bug
