### ISSUE TITLE
Turning on interceptor makes postman request hang indefinitely

### ISSUE THREAD

**Issue by tbillington** [postmanlabs/postman-app-support#884]
Without interceptor the request goes through as normal (POST) but when interceptor is turned on so I can send a Referer header value the request hangs without leaving the application (not received by the target)

If I copy the "build" curl request out and run it in my terminal the request sends successfully.

Postman about:
Version 1.0.5 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Is this happening for all requests, or only a particular request?

**Comment by PudgePacket** [comment]
All requests

**Comment by alexconlin** [comment]
I am experiencing the same issue - both on Mac and Ubuntu. This feature is key for us so that we can use our cookies in chrome.

**Comment by PudgePacket** [comment]
I don't know whether it was restarting my computer, updating chromium or updating postman, but now i'm on 1.0.7 interceptor works again.

**Comment by abhijitkane** [comment]
@alexconlin Are you still facing the issue?

**Comment by AMilkov** [comment]
It is possible to disable the interceptor extension in Chrome, but the flag to use the interceptor stays in Postman.  
After that Postman is not able to send any kind of request to any URL. Restarting Postman do not help.

**Comment by cybersam** [comment]
I am also seeing this on all the requests I have tried. Although the request is hung (showing "Fetching data..." forever), the request does show up in the History, and subsequent requests also show up in the History. If I Reset the request, turn off the Interceptor, and retry the request -- it no longer hangs.

**Comment by abhijitkane** [comment]
@cybersam @AMilkov  Can you share any request (url / method / body) that's causing this problem? We haven't been able to reproduce it yet.

**Comment by artrybalko** [comment]
I just had the same problem after installing the interceptor - with it turned on all requests would hang indefinitely, disabling it made requests go through again.
Then I realized that the interceptor must rely on the same mechanism as the old postman proxy and that I had disabled the postman- header in settings.
Requests started to come through after I enabled the postman-token header in the settings again

**Comment by abhijitkane** [comment]
Thanks for that. What version of Postman are you on? We'll push a fix in the next release.

**Comment by artrybalko** [comment]
Version 2.0.11 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by andersks** [comment]
Also seeing the same issue as well as the fact that WITHOUT the interceptor enabled, you cannot use the environment variables.

**Comment by oliverlockwood** [comment]
Any progress on this?  I'm encountering the issue since upgrading to the new version of Postman.

**Comment by abhijitkane** [comment]
@oliverlockwood What versions of Postman and Interceptor are you using? Do you have this problem even with simple GET requests (w/o any headers)?

**Comment by oliverlockwood** [comment]
@abhijitkane my apologies for the slow reply.  It turned out that it started working fine once I rebooted my computer.

**Comment by vhanded** [comment]
After I rebooted my computer, it works fine, but it came back again later.

**Comment by boonep** [comment]
Same issue here. Ubuntu 14.04 LTS

Postman: 4.1.3
Interceptor: 0.2.18

Also, getting this on simple GET requests without any headers as well.  If I switch off interceptor, I get immediate responses.

**Comment by Christilut** [comment]
Just had the same problem.
Postman about:
4.1.3
linux / x86-64
Chrome 48.0.2564.116
(not sure how to see interceptor version)
Ubuntu 15.10

**Comment by abhijitkane** [comment]
@Christilut To see the interceptor version, head to `chrome://extensions`, and enable 'Developer Mode'.
You should see the version for the Interceptor listed here. Does clicking on `background.html` show any errors in the console?

**Comment by Christilut** [comment]
Hm maybe I uninstalled Interceptor a while ago, can't find it under extensions. Could that be the reason for this bug? Maybe Postman doesn't know Interceptor is gone and thats why it hangs indefinitely?
Postman still thinks it has Interceptor, it doesn't tell me I should install it. The toggle was enabled too.

**Comment by abhijitkane** [comment]
Yes, if you try to toggle the Interceptor off and on again in Postman, it'll show you a warning.

**Comment by Christilut** [comment]
Yeah it does show the warning now. So maybe what I said in my last post could be reason for this bug..

**Comment by abhijitkane** [comment]
Yes, that is correct. Postman has no way of identifying when the Interceptor was uninstalled.
We can check whether the Interceptor is installed each time Postman loads.

**Comment by kobelobster** [comment]
I just got the same error. When having intereceptor activated in postman it's loading and loading. As soon as I disable it (no restart or sth. else) the response comes instantly. 

Is there something I can check for you so you can get more details? I can't click on "About Postman" on OS X though because it is greyed out.

**Comment by abhijitkane** [comment]
@tzfrs To see the interceptor version, head to chrome://extensions, and enable 'Developer Mode'.
You should see the version for the Interceptor listed here. Does clicking on background.html show any errors in the console?
Can you try disabling and enabling the Interceptor from `chrome://extensions`?

**Comment by kobelobster** [comment]
I'm an idiot. I'm on a different working machine which doesn't have the Interceptor extension installed... Sorry for taking your time  😆

**Comment by boonep** [comment]
@abhijitkane no errors from me in background.html

Postman begins working correctly after a restart of my Ubuntu VM, but at some point this error starts cropping up again.  I haven't found the exact steps to recreate.  Trying to keep track.  Let me know if you have any other suggestions for things I can look at to help debug.  Thanks!

**Comment by boonep** [comment]
Found out the issue on my end was caused by a really long request in combination with the "Cancel Request" button not working.  Looks like this has been addressed here: https://github.com/postmanlabs/postman-app-support/issues/767

**Comment by appcrazyprateek** [comment]
can postman interceptor be enable only particular URL , as postman is intercepting all the websites i m browsing because of which its history is increasing resulting in slowness

**Comment by dovy** [comment]
Turned it off and boom it worked for me.  :(

**Comment by icyrizard** [comment]
I sometimes encounter the same issue. Something that worked for me was quickly uninstalling and installing Postman Interceptor.
Working on Mac OS X El Captian 10.11.1, 
Postman Version: 4.2.1
Postman Interceptor Version: 0.2.18
Chrome Version: 50.0.2661.102 (64-bit)

**Comment by appcrazyprateek** [comment]
https://www.codechef.com/snackdown/2016?REF=crazyprateek

**Comment by sonal809** [comment]
Any permanent fix for this issue? I keeps cropping up again and again but there are no definite steps to recreate it.

**Comment by chrisantonellis** [comment]
i'm experiencing the same issue after opening and updating postman today. I do not have postman interceptor installed.

**Comment by eknee** [comment]
Having the same issue as well.  Had to uninstall and re-install the interceptor extension to get things working again.

**Comment by Vishal-Joshi** [comment]
I am having the same issue. After I cancel request, the other requests are hanging indefinitely. 

I am working on Mac FYI.

**Comment by ivanwitzke** [comment]
I'm having the same problem...
OS: Xubuntu 14.04.5 LTS (trusty)
Chrome 54.0.2840.100 (64-bit)
Postman version: 4.8.3

**Comment by Razzwan** [comment]
The same problem...
OS: Ubuntu 14.04 (linux / x86-64)
Postman version: 4.9.0
Chrome 49.0.2623.75

All work right after off "Interceptor"

**Comment by ktersius** [comment]
The same problem...
Version 4.9.0
Postman Interceptor 0.2.20
win / x86-64
Chrome 55.0.2883.75

All work right after off "Interceptor"

Tried 57.0.2942.0 canary (64-bit) and also doesn't work. 

Just tried ARC and it works...

**Comment by mayeaux** [comment]
Same issue on OS X. I was using a proxy for sniffing endpoints which blew it up I think. Reinstalled Interceptor and it works now.

**Comment by mayeaux** [comment]
Yup, can confirm, when I turn on Charles Proxy it breaks Interceptor and the only way to fix it is to reinstall it.

**Comment by octocat-mona** [comment]
I'm unable to download any binary at all.

Steps to reproduce:
* Reinstall Postman Interceptor extension
* In Postman disable and then enable the Interceptor switch
* Do a simple GET [request](http://www.colocenter.nl), works
* Download a [binary](http://www.colocenter.nl/speedtest/100mb.bin) using Send and download, hangs on `loading...` message
* Within 30 seconds Chrome shows a popup saying that the Postman Interceptor Chrome extension crashed.

Is this helpful, can anyone reproduce?

Postman Interceptor version: 0.2.20
Chrome version: 55.0

**Comment by sdnts** [comment]
@kpstolk How large is the file you are trying to download?

**Comment by octocat-mona** [comment]
@madebysid Like the [link](http://www.colocenter.nl/speedtest/100mb.bin) points to, about 100mb 😉

**Comment by thardy** [comment]
I experience this bug frequently as well, and it's very frustrating.  Postman just completely stops working.

Uninstalling Postman Interceptor and reinstalling is the only reliable way to get it working again.

Please fix.

**Comment by thardy** [comment]
I just had it start failing again after a handful of calls, placing Postman in paperweight status yet again.  If it's any help in troubleshooting, I'm using Visual Studio 2015 in debug mode and debugging through my api calls.  Not sure if that has anything to do with the problem, but it couldn't hurt to throw that out.

I've installed Advanced Rest Client with ARC cookie exchange, and that has worked flawlessly so far.  Since this Postman breaking issue has been around for at least a year without any improvement, I suggest the rest of you do the same.

**Comment by cbarbaza** [comment]
Is this issue still under analyses ? I have same issue : with interceptor Postman working quiete well and after time i can't send request until i desabled interceptor

**Comment by daikaixian** [comment]
Disabling and then enabling the extension again in Chrome will fix the issue.

**Comment by JamieFarrelly** [comment]
Over 2 years later and this still randomly happens.

**Comment by numaanashraf** [comment]
We've found an issue that might cause interceptor to stop responding until its re-enabled. Working on a fix.

**Comment by tbillington** [comment]
@JamieFarrelly  I enjoy getting notifications for this every now and again, makes me smile for some reason.

**Comment by georaldc** [comment]
So this is why my Postman requests started to hang indefinitely this morning. Re-toggling the interceptor extension works for me too.

**Comment by dankozlowski** [comment]
Why is this still an issue?!  This thread has been open for over *2 years*!

**Comment by tbillington** [comment]
@dankozlowski Some combination of only affects a tiny amount of users, hard to reproduce, and has a workaround !

Also I think postman is focusing on their non-chrome extension app now, so may not ever get fixed!

**Comment by a85** [comment]
@tbillington That's not exactly true. The Interceptor will be re-written to support native apps and it has some more interesting use cases. We are in the middle of a major release cycle for the native apps and will fix this as soon as we get some time. 

The Interceptor code is open-source too btw so I'd like to welcome contributions (https://github.com/postmanlabs/postman-chrome-interceptor). We have kept this bug open but it seems like it can be caused by different underlying causes.

**Comment by tbillington** [comment]
@a85 Apologies, I knew you're focusing on native apps, didn't realise it would result in improvements to the chrome extension too, awesome :)

**Comment by dankozlowski** [comment]
Excellent to hear the move to native apps -- I'll try there instead.  Thanks for your work!

**Comment by elirenato** [comment]
Same error started to happening for me today. It used to work. I tried a lot of thinks, clear cache, re-install postman interceptor, none of them worked. I had to move to another rest app client.

Below is the error that I see when enabling the Developer mode: 
Error in event handler for runtime.onMessageExternal: ReferenceError: request is not defined
    at sendXhrRequest (chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo/js/background_page.js:304:53)
    at onExternalMessage (chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo/js/background_page.js:530:8)
 
Postman version: 4.11.0
Postman interceptor version: 0.2.21

**Comment by abhijitkane** [comment]
@elirenato We've pushed a fix in version 0.2.22 of the Interceptor. You can head to chrome://extensions, enable 'Developer Mode', and hit 'Update extensions now'.

**Comment by SamvelRaja** [comment]
Since there is no activity in this issue, we are closing this now, feel free to reopen it if needed.

**Comment by maxmilton** [comment]
Still not able to send requests regardless of whether interceptor is turned on or off in either the extension or the app.
```
Linux
Chrome 64
Ext 0.2.24
App 5.3.2
```

**Comment by giowe** [comment]
+1 
same problem here

**Comment by tarunmaini16** [comment]
Facing same issue with interceptor version `0.2.24`
