### ISSUE TITLE
Missing Digest Information in Header

### ISSUE THREAD

**Issue by PixelHomie** [postmanlabs/postman-app-support#932]
I try to send a request using Digest Auth. I've filled the nc, cnonce and qop fields but Postman is not adding them to the Authorization Header after clicking on Refresh Headers.

**Comment by abhijitkane** [comment]
Can you follow the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/ and check if there's any error message being printed to the console?

**Comment by Pixeltechniker** [comment]
If i use the Postman Chrome Extension and send a request in Normal Mode i get a Login Window. If i enter Username and Password there everything works. But in the Digest Auth Mode Postman is not creating a nc Header for example and the Server responds with 401 (Unauthorized) with message "Missing Digest Information"

**Comment by abhijitkane** [comment]
Can you try using the packaged app - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

Are there no errors in the console?

**Comment by Pixeltechniker** [comment]
I have the same issues with the packaged app. Is there any Demo Rest Service available where i can test Postman with Digest Auth?

**Comment by abhijitkane** [comment]
Not that I'm aware of. What happens if you manually edit the header to include the nc/cnonce?

**Comment by abhijitkane** [comment]
There's a service at httpbin.org/digest-auth/auth/u1/p1

I'm able to authenticate successfully. The first request to this URL is made w/o any Auth headers. The server returns a WWW-authenticate header with a nonce, opaque, realm, and qop.

If you then go to the Digest Helper and populate the form with these values (username = u1, password=p1), and add a nc and cnonce, hit 'Refresh headers' and re-send the request, the server returns a 200 OK.

**Comment by Pixeltechniker** [comment]
Yes that works. Is it possible that Postman extract these values automatically? The values are changing for every request so i have to edit them every time before i start a new request.

**Comment by abhijitkane** [comment]
We'll add this soon. The nonce for OAuth1 requests is refresh every time, but not for Digest.

**Comment by AustinBurns** [comment]
Hello,

I am running into a similar issue, except it is with the "algorithm" variable not being sent with the request. I know this does not seem like a big deal as the algorithm is usually MD5, but the framework I am working with requires it and the Postman desktop app is not providing it even though it is set under the Digest Auth helper.

Let me know if you need anymore information.

**Comment by panicou** [comment]
any news on this one ?
I can still not use digest without having to rewrite the values

**Comment by a85** [comment]
This will be fixed with collection-v2. https://github.com/postmanlabs/postman-collection

**Comment by pixelhomie** [comment]
Still not working. The fields "Qop", "Nonce Count" and "Client Nonce" are still not beeing added to the Authorization Header in latest Postman App 4.4.3. I filled the fields and clicked Update Request Button but they still not appearing in the Header :(

**Comment by numaanashraf** [comment]
This should be fixed in latest Mac native release. Will verify and close.

**Comment by jodem** [comment]
I use postman for mac 4.7.1 and I confirm the {{echo_digest_nonce}} is still not working.

**Comment by vegetableman** [comment]
@jodem Thanks for bringing this to our notice. We've identified the issue as well, will update you all.

**Comment by vegetableman** [comment]
@PixelHomie The issue has been fixed for a while. Check out the latest version. Feel free to reopen this issue if it does not work. 

@jodem Misread your issue.`{{echo_digest_nonce}}` is a global variable set through the tests in the `DigestAuth Request` request (in the `Auth: Digest` collection). So, you should the run the said request before running `DigestAuth Success` to get it to work. Let me know if you need any clarifications.

**Comment by fawix** [comment]
Hi, I just tried to use this, facing the same problem as described by this thread. my version is Postman v4.9.1 (Windows App). I really want to use postman but all my APIs use digest and the nonce refreshes very often and I don't look forward to manually updating nonce (we have a few different realms too).

I also noticed that even if I replace the value value of `{{echo_digest_nonce}}` with `blah` it gets authenticated against the postman echo (not a good test). The same is not true for `http://httpbin.org/digest-auth/auth/u1/p1` with which returns an `401` instead (better test)
![digest_echo_postman](https://cloud.githubusercontent.com/assets/735399/21077439/77d781be-bf19-11e6-9759-69ceded87e80.PNG)
![digest_echo_httpbin](https://cloud.githubusercontent.com/assets/735399/21077440/77dbab04-bf19-11e6-90bc-dcff11d112ff.PNG)

**Comment by mdsimpson** [comment]
`{{echo_digest_nonce}}` doesn't work for me either. 

Work-around: I put the following code in the "Tests" tab to grab the nonce value and set it in the environment. Your request fails the first time, then the nonce is set and it succeeds after that. When the nonce expires, then you'll see it fail once on the next request when it resets the nonce. 

```var wwwAuth = postman.getResponseHeader("WWW-Authenticate");
var regEx = /nonce="(.*==)"/;  
var arr = regEx.exec(wwwAuth);  
if (arr && arr.length > 1) {  
  var nonce = arr[1];  
  postman.setEnvironmentVariable("echo_digest_nonce", nonce);  
}
```

**Comment by jamesajones** [comment]
From the beginning I have used a two step process with Digest Authentication build the request build the request from Firefox extensions and send it and get the 401 copy the nonce and sometimes the opaque into the digest fields and resend for success.
